feat: Add delimiter to referrer tag
across-protocol/frontend-v2 pull request #154
Opened 2022-07-06 15:10 UTC by nicholaspai

To make it easier for clients to identify referred transactions, add a delimitter in front of referrer address. By adding in front, this allows referrer-identification logic to be backwards compatible

## Needs QA

**Overview**

**Acceptance Criteria**

### How To Report QA
Testers, use the following templates to pass the pull request or to report issues that require a resolution.
Following these guidelines will help the developer respond more quickly to issues, but you are free to comment
in any way as needed to help resolve issues.

**Reporting QA Issues**

Testers should use Github comments to report issues with the PR. Use screenshots if relevant, you can also
check the [developer console](https://support.airtable.com/hc/en-us/articles/232313848-How-to-open-the-developer-console)
to see if there are any logs which might be related. Use the following template when reporting a problem or issue with the PR.
You submit multiple comments using this template if there are multiple issues.

```
**QA Issue**

**Repro Steps**

**Testing Environment**

```

**Reporting QA Regression**

A regression is something that was working, but now is no longer working due to the new code changes. The breakage
may seem completely unrelated to the pull request, which is why they can go unnoticed during testing.
If you find a regression, or arent sure, report it anyway as an issue and the engineer can decide how to resolve it. 

**Reporting QA Passed**

If you tested and did not find any issues, you will need to signal to the developer that this passed your QA.
Do this by adding comments in the pr. You should communicate to both the developers and other testers what you did during testing. Use the following
template to signal that QA passed your testing.

```
**QA Pass**

**Testing Environment**

```

2022-07-06 17:04 UTC, Tulun commented on src/utils/constants.ts
> +export const referrerDelimitterHex = "0xaaaabbbbccccdddd";
Would this cause major issues if this string changed without notice?

2022-07-06 17:17 UTC, nicholaspai commented on src/utils/format.ts
> +  return ethers.utils.hexConcat([dataHex, referrerDelimitterHex, tagHex]);
good call

2022-07-06 17:17 UTC, nicholaspai commented on src/utils/constants.ts
> +export const referrerDelimitterHex = "0xaaaabbbbccccdddd";
minor issues i think: the API that @amateima built would just have to be aware of all historical delimitters we've used in past.

2022-07-06 18:32 UTC, Tulun commented on src/utils/constants.ts
> +export const referrerDelimitterHex = "0xaaaabbbbccccdddd";
Should we have a way of tracking this then?

2022-07-07 12:14 UTC, daywiss reviewed
im not totaly convinced this is the way to go.  you still need to support the previous way, especially if you expect third parties to be using their own referral making code

2022-07-07 12:14 UTC, daywiss commented on src/utils/constants.ts
> +export const referrerDelimitterHex = "0xaaaabbbbccccdddd";
delimitter  should be delimiter

2022-07-07 15:19 UTC, nicholaspai commented on src/utils/constants.ts
> +export const referrerDelimitterHex = "0xaaaabbbbccccdddd";
what do you mean by "delimitter should be delimiter" @daywiss ?

2022-07-07 16:29 UTC, amateima approved these changes

2022-07-07 18:54 UTC, nicholaspai commented on src/utils/constants.ts
> +export const referrerDelimitterHex = "0xaaaabbbbccccdddd";
oh lol

2022-07-07 23:16 UTC, mrice32 approved these changes
LGTM!

2022-07-08 09:25 UTC, amateima requested changes
<img width="680" alt="Screenshot 2022-07-08 at 12 25 08" src="https://user-images.githubusercontent.com/89395931/177961849-6b6d4cba-bb91-4208-8fa2-040c0b099192.png">

It breaks the send tab

2022-07-08 14:02 UTC, amateima approved these changes

2022-07-08 14:09 UTC, merged