feat: align Tables; Refactor Table to be exportable and Baseline
across-protocol/frontend-v2 pull request #189
Opened 2022-07-26 21:57 UTC by Tulun

Overview:

More closely align the Referral and Transaction Tables. Also refactored the baseline component to be more generalizable and use it as an Example. If you need to go beyond the Baseline, take the exported styled components and build as needed.
<img width="1468" alt="Screen Shot 2022-07-26 at 2 56 44 PM" src="https://user-images.githubusercontent.com/12792146/181119465-14f738b6-3516-49a6-8901-25516e53011f.png">

2022-07-26 22:00 UTC, Tulun commented on src/App.tsx
> +
I had issues with my TX table until I added these envs, we should have a check on these imo.

2022-07-27 11:53 UTC, amateima requested changes
<img width="485" alt="Screenshot 2022-07-27 at 14 32 37" src="https://user-images.githubusercontent.com/89395931/181240101-7fec95c6-1a70-4d5c-986d-a7d0e599ba94.png">

I'll ask Tim if we need to keep the accordion row style or use the same behaviour as the rewards table

2022-07-27 11:53 UTC, amateima commented on src/components/Pagination/Pagination.styles.tsx
>  import styled from "@emotion/styled";
From what I see, the styles from `RewardTablePagination.styles.tsx` are identical to the components from this file. Can we delete most of the components from `RewardTablePagination.styles.tsx` and use the ones from here?

2022-07-27 11:53 UTC, amateima commented on src/views/Transactions/TransactionsTable/createTransactionTableJSX.tsx
>            <TableLogo src={token?.logoURI} alt={`${token?.name}_logo`} />{" "}
<img width="178" alt="Screenshot 2022-07-27 at 14 33 45" src="https://user-images.githubusercontent.com/89395931/181239715-a59afd78-8e28-4378-a486-1e1446379082.png">

Let's display the token symbol here

2022-07-27 17:45 UTC, Tulun commented on src/components/Pagination/Pagination.styles.tsx
>  import styled from "@emotion/styled";
Yup, good call, as the styles are the default now it can be removed

2022-07-27 17:46 UTC, Tulun commented on src/views/Transactions/TransactionsTable/createTransactionTableJSX.tsx
>            <TableLogo src={token?.logoURI} alt={`${token?.name}_logo`} />{" "}
> <img alt="Screenshot 2022-07-27 at 14 32 37" width="485" src="https://user-images.githubusercontent.com/89395931/181240101-7fec95c6-1a70-4d5c-986d-a7d0e599ba94.png">
> 
> I'll ask Tim if we need to keep the accordion row style or use the same behaviour as the rewards table

That's fine -- I just left it as is as the data we're displaying is a bit different, but if we wanna scroll instead that's fine.

2022-07-27 18:05 UTC, Tulun commented on src/views/Transactions/TransactionsTable/createTransactionTableJSX.tsx
>            <TableLogo src={token?.logoURI} alt={`${token?.name}_logo`} />{" "}
@amateima chatted with Tim, he's happy with the current look, may do some redesign at a later date.

2022-07-27 18:46 UTC, daywiss approved these changes
did not notice any issues in my testing, code lgtm, nice work

2022-07-28 08:44 UTC, amateima approved these changes
Looks good, but let's increase the bottom padding of this wrapper because the page size dropdown doesn't have enough room. I think it's 4rem on the Rewards Page

<img width="1309" alt="Screenshot 2022-07-28 at 11 42 14" src="https://user-images.githubusercontent.com/89395931/181462146-f6704e01-7cef-4b92-bba3-8b6fbb46350c.png">

2022-07-28 16:16 UTC, merged