feat: make navbar sticky
across-protocol/frontend-v2 pull request #191
Opened 2022-07-27 21:36 UTC by Tulun

Created useScrollPosition hook, when SP > 0 add a border to the navbar
<img width="1477" alt="Screen Shot 2022-07-27 at 2 36 10 PM" src="https://user-images.githubusercontent.com/12792146/181376898-8062babf-c919-4109-bbc2-5255f43f3cc1.png">

2022-07-28 08:56 UTC, amateima requested changes
All the content across the web app is being cut now due to the new `fixed` positioning

<img width="1792" alt="Screenshot 2022-07-28 at 11 50 37" src="https://user-images.githubusercontent.com/89395931/181465018-b9e09ee0-94c6-42f4-8ce1-5acebce2f8fd.png">
<img width="1792" alt="Screenshot 2022-07-28 at 11 51 03" src="https://user-images.githubusercontent.com/89395931/181465025-a42aa151-ae6a-4e32-bda3-327b00cfc9d9.png">

For example, the top padding of this wrapper should include the header height too.

<img width="1310" alt="Screenshot 2022-07-28 at 11 52 34" src="https://user-images.githubusercontent.com/89395931/181465212-4ac5f71c-9a58-4bfc-a37b-84e6b6f51c26.png">

2022-07-28 08:56 UTC, amateima commented on src/components/Header/Header.styles.tsx
> +  z-index: 1000;
Let's put in the README file the z-index values we use for various components: headers, tooltips, pup-ups, toasts, etc (I think it's only the header for now). We'll add pop-ups in the near future and we'll have to guess the z-index values to make them positioned on top of everything

2022-07-28 09:00 UTC, amateima requested changes

2022-07-28 09:00 UTC, amateima commented on src/components/Header/Header.styles.tsx
> +    return scrollPosition > 0 ? "1px solid #4d4f56" : "none";
I think this should be `scrollPosition > 0 ? "1px solid #4d4f56" : "1px solid transparent"`. Making it `none` decreases the height of the header content on scroll which produces an annoying effect

2022-07-28 11:49 UTC, daywiss commented
running into some of the same issues as alex, will re-test once those are addressed

2022-07-28 16:23 UTC, Tulun commented on src/components/Header/Header.styles.tsx
> +    return scrollPosition > 0 ? "1px solid #4d4f56" : "none";
Fair, changed.

2022-07-28 16:24 UTC, Tulun commented on src/components/Header/Header.styles.tsx
> +  z-index: 1000;
Added.

2022-07-28 16:36 UTC, Tulun commented
> running into some of the same issues as alex, will re-test once those are addressed

@daywiss feel free to review, fixed the issues.

2022-07-28 16:37 UTC, Tulun commented
@daywiss @amateima also changed the display to ref and copy to ref as that was requested and it's a very minor change.

2022-07-28 17:40 UTC, daywiss commented
im seeing a gap in the footer when the browser is at certain heights 
![image](https://user-images.githubusercontent.com/4429761/181602455-54cd661a-c8e2-4937-9f62-3204418d0912.png)

2022-07-28 17:45 UTC, Tulun commented
> im seeing a gap in the footer when the browser is at certain heights ![image](https://user-images.githubusercontent.com/4429761/181602455-54cd661a-c8e2-4937-9f62-3204418d0912.png)
> 
> this is at roughly 1000px height

haha just fixed this.

2022-07-29 01:08 UTC, daywiss approved these changes
lgtm

2022-07-29 13:05 UTC, amateima commented
> @daywiss @amateima also changed the display to ref and copy to ref as that was requested and it's a very minor change.

you can make it as part of a separate PR, but the referral link box needs some minor changes. [See here](https://linear.app/uma/issue/ACX-90/add-ref-as-supported-query-parameter-for-the-referrer-address) (4 address characters, the container box width, the URL button left/right padding)

2022-07-29 13:05 UTC, amateima approved these changes

2022-07-29 15:32 UTC, merged