feat: Implement Rewards Banner warning behind env var.
across-protocol/frontend-v2 pull request #192
Opened 2022-07-28 19:23 UTC by Tulun

<img width="1493" alt="Screen Shot 2022-07-28 at 12 22 45 PM" src="https://user-images.githubusercontent.com/12792146/181620599-f10e8e4f-4f44-4411-a82a-5e7c666a3049.png">

Banner hidden behind REACT_APP_REWARDS_BANNER_WARNING = true. Only shows on /rewards page.

2022-07-28 19:46 UTC, nicholaspai approved these changes
LGTM whenever we want to start displaying the warning

2022-07-28 19:46 UTC, nicholaspai commented on src/components/Banner/Banner.tsx
> +  if (!container.current) {
Out of curiosity, does it increase performance to exit earlier if !container above where it's first defined?

2022-07-28 19:50 UTC, Tulun commented on src/components/Banner/Banner.tsx
> +  if (!container.current) {
Hm it might, not sure if it would be a huge diff.

2022-07-29 12:22 UTC, daywiss commented
@nicholaspai @Tulun i've added the env to enable the banner just for preview and development

2022-07-29 12:33 UTC, daywiss commented
looks good, but just fyi the banner at the top extends the length of the page causing a scrollbar to show up. this was the same issue with the navbar that was fixed recently.  you could fix in this pr or make an issue for it, up to you

2022-07-29 12:34 UTC, daywiss approved these changes
only issue is that banner causes page length to be beyond window height, you can fix in this pr or make an issue for it since its pretty minor

2022-07-29 12:42 UTC, amateima requested changes

2022-07-29 12:42 UTC, amateima commented on src/components/Banner/Banner.styles.tsx
> +      font-size: ${13 / 16}rem;
this should be 14, not 13

2022-07-29 12:42 UTC, amateima commented on src/components/Banner/Banner.styles.tsx
> +    @media ${QUERIES.mobileAndDown} {
let's use the new breakpoints from the design. From what I could see in the design, the styles are changed only on mobile ( <= 428px )

2022-07-29 16:51 UTC, Tulun commented on src/components/Banner/Banner.styles.tsx
> +    @media ${QUERIES.mobileAndDown} {
I've changed this but it won't look good at all breakpoints.

2022-08-02 17:15 UTC, amateima approved these changes

2022-08-02 17:15 UTC, merged