docs: improve "getting-started" experience
across-protocol/frontend-v2 pull request #199
Opened 2022-08-03 14:01 UTC by dohaki

While trying to run the app locally, I noticed some things that this tries to improve:
- more inviting README file
- example .env file to easily get started
- refined docs on which env vars are required/optional

2022-08-03 14:45 UTC, nicholaspai commented on .env.example
> +REACT_APP_HUBPOOL_CHAINID=1
Should this be defaulted to 1 in the app? I can't imagine that this is ever changed in practice (i'm not sure app would work on testnets currently)

2022-08-03 14:47 UTC, nicholaspai commented on src/utils/constants.ts
> +  process.env.REACT_APP_CHAIN_42161_PROVIDER_URL,
Its strange we only check for 137/42161. Should we also check for 1/288/10?

2022-08-03 14:47 UTC, nicholaspai reviewed
Looks great, will wait for @Tulun to review

2022-08-03 15:18 UTC, amateima commented on src/utils/constants.ts
> +  process.env.REACT_APP_CHAIN_42161_PROVIDER_URL,
@nicholaspai these two providers were overwritten with custom provider urls because they had poor performance on the tx history page while fetching events. We dont have to check for 1, 288, 10 because we're using the default Infura providers for them

2022-08-03 15:21 UTC, amateima approved these changes

2022-08-03 15:21 UTC, amateima commented on CONTRIBUTING.md
> +```
Personally I'd put these lines back to the readme file, but I don't have a strong opinion about it

2022-08-03 15:44 UTC, Tulun requested changes
Couple comments.

2022-08-03 15:44 UTC, Tulun commented on .env.example
> +### REQUIRED ENV VARS ###
I would probably comment on each of these potential good values (or set of expected values ie: 
true | false)  given this is an example.

2022-08-03 15:44 UTC, Tulun commented on src/utils/constants.ts
> +  process.env.REACT_APP_CHAIN_42161_PROVIDER_URL,
Maybe we should document this in the README @amateima ?

2022-08-03 15:44 UTC, Tulun commented on CONTRIBUTING.md
> +- Try to keep PRs focused on a single feature, bug, or issue.
We no longer use shortcut.

2022-08-03 15:54 UTC, dohaki commented on CONTRIBUTING.md
> +```
There is still a [`Getting started` section in the README](https://github.com/across-protocol/frontend-v2/blob/a83d6d541fbc832aafe7c063a66775d9bc7d41dd/README.md#getting-started) that contains most of these lines (except the build step). Should I still move these back?

2022-08-03 18:17 UTC, daywiss commented on CONTRIBUTING.md
> +```
i can understand the reason for putting this into the contributors section, because this is an app not a library, the readme should probably be high level for end users, while contributors are the developers.

2022-08-03 18:18 UTC, daywiss commented on .env.example
> +#########################
im wary about having 2 sources of truth, one in the example and one in the contributor file. it just makes it error prone to maintain as envs change.  You could just use this as the source of truth for documentation and link to it in the docs

2022-08-04 07:01 UTC, dohaki commented on .env.example
> +REACT_APP_HUBPOOL_CHAINID=1
I changed it so that we default to 1 if this env var is not set. Therefore this env var is not required but optional now.

2022-08-04 07:03 UTC, dohaki commented on src/utils/constants.ts
> +  process.env.REACT_APP_CHAIN_42161_PROVIDER_URL,
I added some more information in the comments for these env vars. See https://github.com/across-protocol/frontend-v2/pull/199/files#diff-a3046da0d15a27e89f2afe639b25748a7ad4d9290af3e7b1b6c1a5533c8f0a8cR15-R21 and let me know if this suffices.

2022-08-04 07:04 UTC, dohaki commented on CONTRIBUTING.md
> +```
Ok, I moved it back into the README and removed it from the CONTRIBUTING doc for now.

2022-08-04 07:06 UTC, dohaki commented on .env.example
> +### REQUIRED ENV VARS ###
I added some more information on potential good values in the example env var file https://github.com/across-protocol/frontend-v2/pull/199/files#diff-a3046da0d15a27e89f2afe639b25748a7ad4d9290af3e7b1b6c1a5533c8f0a8cR5-R21. Let me know if this is what thought you of.

2022-08-04 07:06 UTC, dohaki commented on CONTRIBUTING.md
> +- Try to keep PRs focused on a single feature, bug, or issue.
Changed to linear

2022-08-04 07:09 UTC, dohaki commented on .env.example
> +#########################
Yea good point. I removed the env var docs from the README/CONTRIBUTING and will keep the example file as the single source of truth.

2022-08-04 12:11 UTC, daywiss approved these changes

2022-08-04 12:41 UTC, james-a-morris approved these changes
This PR is succinct. 

Creating an example env file will help new developers/contributors better onboard into this repository. 

I agree with @dohaki 's decision to place the instructions to build the frontend-v2 in a separate contributing markdown file. Additionally, the decision to remove information related to contributions from the main readme feels like a great way to reduce redundant info from the codebase.

Finally, @dohaki has further asserted the optional/required nature of several env variables (including the Hubpool Chain Id) within the contstants file. I think that's a vital step toward keeping the docs/codebase in sync.

2022-08-04 16:06 UTC, nicholaspai commented on src/utils/constants.ts
> +  process.env.REACT_APP_CHAIN_42161_PROVIDER_URL,
Great stuff @dohaki

2022-08-04 16:06 UTC, nicholaspai approved these changes
LGTM

2022-08-04 16:48 UTC, Tulun commented on .env.example
> +### REQUIRED ENV VARS ###
Yep, I might instead of saying "alchemy" I would put like: https://mainnet.infura.io/v3/<infura-key>

2022-08-04 16:50 UTC, Tulun approved these changes

2022-08-05 08:39 UTC, dohaki commented on .env.example
> +### REQUIRED ENV VARS ###
done

2022-08-05 08:55 UTC, merged