feat: create toast widget + hook up referrer notification to new Toast.
across-protocol/frontend-v2 pull request #213
Opened 2022-08-12 23:44 UTC by Tulun

## Needs QA

**Overview**
Add new toast element to across UI.

<img width="1048" alt="Screen Shot 2022-08-12 at 4 12 06 PM" src="https://user-images.githubusercontent.com/12792146/184456658-1ebd361a-f846-47f7-9609-9fbd8583b83b.png">
<img width="450" alt="Screen Shot 2022-08-12 at 4 11 51 PM" src="https://user-images.githubusercontent.com/12792146/184456659-9c295604-f404-4254-aa04-dcb6f19c2e9c.png">

**Acceptance Criteria**
1. Toast should display when you put in a bad query string (e.g: ?ref=0x123432142 or referrer=0x123412314) of a bad address.
2. Toast should display an when you put in an ENS value that doesn't resolve (e.g: ?ref=nonsensestring.eth  or ?referrer=nonsensestring.eth)

### How To Report QA
Testers, use the following templates to pass the pull request or to report issues that require a resolution.
Following these guidelines will help the developer respond more quickly to issues, but you are free to comment
in any way as needed to help resolve issues.

**Reporting QA Issues**

Testers should use Github comments to report issues with the PR. Use screenshots if relevant, you can also
check the [developer console](https://support.airtable.com/hc/en-us/articles/232313848-How-to-open-the-developer-console)
to see if there are any logs which might be related. Use the following template when reporting a problem or issue with the PR.
You submit multiple comments using this template if there are multiple issues.

```
**QA Issue**

**Repro Steps**

**Testing Environment**

```

**Reporting QA Regression**

A regression is something that was working, but now is no longer working due to the new code changes. The breakage
may seem completely unrelated to the pull request, which is why they can go unnoticed during testing.
If you find a regression, or arent sure, report it anyway as an issue and the engineer can decide how to resolve it. 

**Reporting QA Passed**

If you tested and did not find any issues, you will need to signal to the developer that this passed your QA.
Do this by adding comments in the pr. You should communicate to both the developers and other testers what you did during testing. Use the following
template to signal that QA passed your testing.

```
**QA Pass**

**Testing Environment**

```

2022-08-13 15:05 UTC, Penny-Panda commented
**QA Report**

Found AssertionError for goerli-frontend-v2, dapp doesn't load up.
And, Toast doesn't show up when adding false/incorrect/invalid ENS names (as shown in the pictures), when wallet is not connected. 
It shows up when attempting to connect wallet, and works fine when wallet is connected.
It doesn't work for DNSSEC ENS domains though, such as "truts.xyz"


**Screenshots**

frontend-v2:
![image](https://user-images.githubusercontent.com/25153462/184499599-0368793a-31b0-4260-b461-e1f66f296878.png)
![image](https://user-images.githubusercontent.com/25153462/184499644-bbf68cc7-38b6-4993-b2b0-eb6478bb3325.png)
![image](https://user-images.githubusercontent.com/25153462/184499675-64686e11-4a75-4ea6-bdae-e76a2be77125.png)
![image](https://user-images.githubusercontent.com/25153462/184499729-b5b55258-c994-45e2-ac42-a20a1e6d8621.png)
![image](https://user-images.githubusercontent.com/25153462/184499752-35f7b9a1-fc22-4c0a-9a8d-70cf79a9ab9a.png)
![image](https://user-images.githubusercontent.com/25153462/184499795-5be97b69-9574-4488-ac79-e01a3552ca68.png)




goerli-frontend-v2:
![image](https://user-images.githubusercontent.com/25153462/184499559-44acacac-0a77-44e6-af6f-c159d319482e.png)

**Testing Environment**
Google Chrome
Version 104.0.5112.81 (Official Build) (64-bit)
Desktop

2022-08-15 12:53 UTC, daywiss commented on src/components/Toast/useToast.tsx
> +  console.log("list", list);
stray

2022-08-15 12:53 UTC, daywiss commented on src/hooks/useReferrer.ts
> +              addToast({
i dont think the userReferrer hook should depend on the toast component, can you find another way to trigger it, perhaps in a higher level component

2022-08-15 12:53 UTC, daywiss commented on src/components/Toast/useToast.tsx
> +      setCid((pv) => pv + 1);
im not sure i understand the reason for this, do you just need a unique id for react or something?

2022-08-15 13:35 UTC, amateima requested changes

2022-08-15 13:35 UTC, amateima commented on src/assets/icons/cross.svg
> +</svg>
By looking at the Figma design, this icon should come in 2 sizes: 16px and 20px

2022-08-15 13:35 UTC, amateima commented on src/components/Toast/Toast.styles.tsx
> +  z-index: 999999;
Please add the used z-index to the contributing.md file where all z-indexes are mentioned

2022-08-15 13:35 UTC, amateima commented on src/components/Toast/Toast.styles.tsx
> +  box-shadow: 0px 12px 24px rgba(0, 0, 0, 0.24);
why the container needs to have a box shadow if the background is transparent? My understanding is that the `ToastContainer` can contain multiple toasts messages, the box-shadow being needed for each toast message, not the whole container

2022-08-15 13:35 UTC, amateima commented on src/components/Toast/Toast.styles.tsx
> +  border-radius: 16px;
is the border radius needed for the container itself?

2022-08-15 13:35 UTC, amateima commented on src/components/Toast/Toast.styles.tsx
> +      `;
not sure I agree with this behaviour. In my view, the container should always be displayed on the screen having the clicks disabled and the visual effects should be applied to the toast messages directly

2022-08-15 13:35 UTC, amateima commented on src/components/Toast/Toast.styles.tsx
> +  width: 300px;
font-weight and line-height are not as in the design. Also mobile breakpoint styles are missing

2022-08-15 13:35 UTC, amateima commented on src/components/Toast/Toast.styles.tsx
> +    margin-left: 12px;
I don't see why the width should be set to 95%. Seems like a random value

2022-08-15 13:35 UTC, amateima commented on src/components/Toast/Toast.tsx
> +            <ToastElement>
Can't we have a single ToastWrapper component? Why a second ToastElement component is necessary ?

2022-08-15 13:35 UTC, amateima commented on src/hooks/useReferrer.ts
> +              addToast({
I agree. useToast should be pulled out and used in the same component where useReferrer is called

2022-08-15 13:35 UTC, amateima commented on src/components/Toast/Toast.styles.tsx
> +  color: #c5d5e0;
line-height is not as in the design. Also mobile breakpoint styles are missing

2022-08-15 13:35 UTC, amateima commented on src/components/Toast/Toast.styles.tsx
> +    margin-left: 12px;
the padding should be changed here as well

2022-08-15 13:35 UTC, amateima commented on src/components/Toast/useToast.tsx
> +      setCid((pv) => pv + 1);
I'm not sure why we need it too

2022-08-15 13:35 UTC, amateima commented on src/components/Toast/useToast.tsx
> +function useToastManager() {
Based on a previous discussion I had with Tim, he wants the toast message to behave very similar to the toasts from Linear app. You can see an example if you go to any issue and click the branch name button

<img width="460" alt="Screenshot 2022-08-15 at 16 29 08" src="https://user-images.githubusercontent.com/89395931/184644772-fffe3404-bff0-40ee-aa4d-755c24659697.png">

You'll see that we need to provide the option for the toasts to auto-hide after some time. Also, if you click on the same button multiple times, you'd still have a single toast being displayed alongside a discrete scaling effect. In order to achieve this behaviour, I think an optional id string should be provided.

2022-08-15 17:06 UTC, Tulun commented on src/hooks/useReferrer.ts
> +              addToast({
Sure, it can be composed that way.

2022-08-15 17:07 UTC, Tulun commented on src/components/Toast/useToast.tsx
> +      setCid((pv) => pv + 1);
The reason here is because right now you can do an array of Toast elements rendering.

When you delete them, you can delete them in any order, so we need to make sure the ID is unique (as you can have a stack of like 1, 3, 7, 8 , 10 notifications for example) so you don't delete two notifications when you click "X"

2022-08-15 17:07 UTC, Tulun commented on src/components/Toast/Toast.styles.tsx
> +  z-index: 999999;
Yep, good call.

2022-08-15 17:07 UTC, Tulun commented on src/components/Toast/Toast.styles.tsx
> +  box-shadow: 0px 12px 24px rgba(0, 0, 0, 0.24);
Right I'll move it down.

2022-08-15 17:09 UTC, Tulun commented on src/components/Toast/Toast.tsx
> +            <ToastElement>
because there's the container (which contains all Toasts), and the Toasts themselves, which can have CSS changes based on type (IE: warning vs error). The border around the toast changes.

2022-08-15 17:10 UTC, Tulun commented on src/components/Toast/useToast.tsx
> +function useToastManager() {
I see. This was definitely not documented anywhere, but this toast can be redesigned to just show 1 notification at a time.

My question would be is what would happen if you get 2 pertinent warnings at once? As I think the Linear way just overwrites the toast.

2022-08-15 17:12 UTC, Tulun commented on src/components/Toast/useToast.tsx
> +function useToastManager() {
Oh I see the effect. I dunno this is weird. You'd have to know the bug is from the same error, but what if you make a 2nd request and get a similar response? It might be hard to know if the error is generated from the same *type* of problem.

2022-08-15 17:49 UTC, Tulun commented
> **QA Report**
> 
> Found AssertionError for goerli-frontend-v2, dapp doesn't load up. And, Toast doesn't show up when adding false/incorrect/invalid ENS names (as shown in the pictures), when wallet is not connected. It shows up when attempting to connect wallet, and works fine when wallet is connected. It doesn't work for DNSSEC ENS domains though, such as "truts.xyz"
> 
> **Screenshots**
> 
> frontend-v2: ![image](https://user-images.githubusercontent.com/25153462/184499599-0368793a-31b0-4260-b461-e1f66f296878.png) ![image](https://user-images.githubusercontent.com/25153462/184499644-bbf68cc7-38b6-4993-b2b0-eb6478bb3325.png) ![image](https://user-images.githubusercontent.com/25153462/184499675-64686e11-4a75-4ea6-bdae-e76a2be77125.png) ![image](https://user-images.githubusercontent.com/25153462/184499729-b5b55258-c994-45e2-ac42-a20a1e6d8621.png) ![image](https://user-images.githubusercontent.com/25153462/184499752-35f7b9a1-fc22-4c0a-9a8d-70cf79a9ab9a.png) ![image](https://user-images.githubusercontent.com/25153462/184499795-5be97b69-9574-4488-ac79-e01a3552ca68.png)
> 
> goerli-frontend-v2: ![image](https://user-images.githubusercontent.com/25153462/184499559-44acacac-0a77-44e6-af6f-c159d319482e.png)
> 
> **Testing Environment** Google Chrome Version 104.0.5112.81 (Official Build) (64-bit) Desktop

Thanks for the QA!

So we wait for the provider to be defined so the fact it only works when connected is fine -- in fact since you can't make a transaction until you are connected, it seems fine to wait until the user has clicked through before peppering them with a warning / error.

I'm not as familiar with the .xyz extension stuff, is this supported out of the box with ethers? Or how is this normally resolved?

2022-08-15 22:09 UTC, Tulun commented on src/components/Toast/useToast.tsx
> +  console.log("list", list);
fixed

2022-08-15 22:24 UTC, Tulun commented on src/components/Toast/useToast.tsx
> +      setCid((pv) => pv + 1);
Tagged y'all on a topic in linear.

2022-08-15 22:33 UTC, Tulun commented on src/hooks/useReferrer.ts
> +              addToast({
Adjusted

2022-08-15 22:47 UTC, Tulun commented on src/components/Toast/Toast.styles.tsx
> +  border-radius: 16px;
Removed.

2022-08-15 22:47 UTC, Tulun commented on src/components/Toast/Toast.styles.tsx
> +      `;
What did you have in mind instead?

2022-08-15 22:59 UTC, Tulun commented on src/components/Toast/Toast.styles.tsx
> +  color: #c5d5e0;
Adjusted.

2022-08-15 23:00 UTC, Tulun commented on src/hooks/useReferrer.ts
> +      if (r.slice(-4) === ".eth") {
I think we aren't too worried about general users testing referrer links on testnets :)

2022-08-17 01:32 UTC, daywiss approved these changes
looks good to me, just minor nits

2022-08-17 01:32 UTC, daywiss commented on src/components/Toast/useToast.tsx
> +  const [list, setList] = useState<ToastProperties[]>([
this default state while good for testing will need to be changed before merge to master

2022-08-17 01:32 UTC, daywiss commented on src/hooks/useReferrer.ts
> +      if (r.slice(-4) === ".eth") {
i feel like this check isnt necessary since it will fail when `resolveName` fails

2022-08-17 12:45 UTC, amateima commented on src/assets/icons/info-sm.svg
> +</svg>
small nit, don't we already have an [info-16](https://github.com/across-protocol/frontend-v2/blob/8a4dd9fe36e55827a77a6e98f1e86833d3cdad73/src/assets/icons/info-16.svg) icon?

2022-08-17 18:20 UTC, Tulun commented on src/hooks/useReferrer.ts
> +      if (r.slice(-4) === ".eth") {
Removed.

2022-08-17 18:21 UTC, Tulun commented on src/assets/icons/info-sm.svg
> +</svg>
Wasn't sure this was exactly the same, adjusted.

2022-08-17 18:21 UTC, merged