feat(claim): disconnected + ineligible state
across-protocol/frontend-v2 pull request #229
Opened 2022-08-22 15:03 UTC by dohaki

This PR adds two view components to the claim aka airdrop page:
- when user is disconnected
- when user is ineligible

A lot of data is still mocked and this covers mostly the presentational layer.

2022-08-22 21:42 UTC, Tulun commented on src/views/Claim/components/Card.tsx
> +
use new QUERIESV2.

2022-08-22 21:43 UTC, Tulun commented on src/views/Claim/components/NotEligibleWallet.tsx
> +  display: flex;
Shouldn't have to specify height I think with Flexbox.

2022-08-22 21:47 UTC, Tulun commented
<img width="184" alt="Screen Shot 2022-08-22 at 2 45 24 PM" src="https://user-images.githubusercontent.com/12792146/186024491-019a27be-afa8-4bdd-9041-df6c88166a44.png">

Info icons should have tooltips. Just stub in a title / body we can update copy later.

Examples in the referral section or the Stake section.

2022-08-22 22:02 UTC, Tulun commented
<img width="63" alt="Screen Shot 2022-08-22 at 3 00 17 PM" src="https://user-images.githubusercontent.com/12792146/186026426-105798d0-0a06-4c57-a222-1fbb94ad0431.png">

Hmm I think you layered these 2 svgs, it might be better if they were composed into 1 file, as it's unlikely they'll ever be displaced from the other.

2022-08-23 09:48 UTC, dohaki commented on src/views/Claim/components/NotEligibleWallet.tsx
> +          distributed by <a href="/">visiting our FAQ</a>.
It does actually 🤔 
<img width="639" alt="image" src="https://user-images.githubusercontent.com/17645687/186127773-aa9cf212-dba6-4a0f-bd0c-e41d35298b67.png">

2022-08-23 09:48 UTC, dohaki commented on src/views/Claim/Claim.styles.tsx
> +  padding-bottom: ${24 / 16}rem;
Yes will adapt to the new `QUERIESV2` constant.

2022-08-23 09:55 UTC, dohaki commented on src/views/Claim/components/NotEligibleWallet.tsx
> +  display: flex;
You usually don't, but in this case, because I am setting a background image that should scale with the parent container size, I need this fixed height.

2022-08-23 09:58 UTC, dohaki commented
> <img alt="Screen Shot 2022-08-22 at 3 00 17 PM" width="63" src="https://user-images.githubusercontent.com/12792146/186026426-105798d0-0a06-4c57-a222-1fbb94ad0431.png">
> 
> Hmm I think you layered these 2 svgs, it might be better if they were composed into 1 file, as it's unlikely they'll ever be displaced from the other.

Yea, I created a composable component that allows you to set any arbitrary icon pairs for this. You don't think there will be different asset pairs that will be displayed like that?

2022-08-23 14:50 UTC, dohaki commented on src/views/Claim/Claim.tsx
>        <Title>Airdrop</Title>
fixed 👍 thanks for catching this

2022-08-23 14:57 UTC, dohaki commented on src/components/Header/Header.tsx
> +import { ReactComponent as GiftBoxIcon } from "assets/icons/gift.svg";
Yes makes sense. Didn't know that we have feather icons included 👍

2022-08-23 20:55 UTC, Tulun commented on src/views/Claim/components/NotEligibleWallet.tsx
> +  display: flex;
Gotcha!

2022-08-23 20:55 UTC, Tulun commented on src/views/Claim/hooks/useClaimView.tsx
> +  >({ status: "idle" });
I'd probably pull this out into its own type.

2022-08-23 20:56 UTC, Tulun commented
> > <img alt="Screen Shot 2022-08-22 at 3 00 17 PM" width="63" src="https://user-images.githubusercontent.com/12792146/186026426-105798d0-0a06-4c57-a222-1fbb94ad0431.png">
> > Hmm I think you layered these 2 svgs, it might be better if they were composed into 1 file, as it's unlikely they'll ever be displaced from the other.
> 
> Yea, I created a composable component that allows you to set any arbitrary icon pairs for this. You don't think there will be different asset pairs that will be displayed like that?

Oh I see, that's totally fair. Yeah we might.

2022-08-23 20:56 UTC, Tulun approved these changes
just a nit, lgtm.

2022-08-23 22:05 UTC, amateima requested changes
Mostly are small comments, the most important one is about the missing footer.

Also, please ask Tim to review the static components you build so far! He needs only the preview URL and the exact list of the items to be reviewed.

2022-08-23 22:05 UTC, amateima commented on src/components/IconPair/IconPair.tsx
> +`;
Tim will see that the border around ACX icon is missing 😄 

<img width="164" alt="Screenshot 2022-08-24 at 00 58 56" src="https://user-images.githubusercontent.com/89395931/186273874-c3dbd8be-f81c-4d99-9e49-3c3b5848d5ac.png">

2022-08-23 22:05 UTC, amateima commented on src/views/Claim/Claim.styles.tsx
> +  margin: 64px auto;
I didn't see why does it happen, but the margin is not applied on the bottom side. I guess this will go away once you refactor this component according to my above comment

2022-08-24 09:54 UTC, dohaki commented on src/assets/arrow-top-right.svg
> +</svg>
Yes you are right, will replace.

2022-08-24 10:06 UTC, dohaki commented on src/views/Claim/components/DisconnectedWallet.tsx
> +const LearnMoreLink = styled.a`
Ok, yea I created a new component that is shared between these views.

2022-08-24 10:16 UTC, dohaki commented on src/components/IconPair/IconPair.tsx
> +`;
oh wow good catch! didn't see that border 👍

2022-08-24 14:46 UTC, amateima approved these changes

2022-08-24 15:24 UTC, merged