feat: upgrade onboard to latest version
across-protocol/frontend-v2 pull request #237
Opened 2022-08-24 23:17 UTC by Tulun

1. Upgrade old version of onboard to new version.
2. Requires extensive testing of all onchain operations.

TODO (will update before full PR):

1. Styling of Onboard modal.
2. Removing all unnecessary old v1 code.

2022-08-24 23:20 UTC, Tulun commented on src/utils/onboardV2.ts
> +
Some typing from the docs. I can delete if required.

2022-08-24 23:20 UTC, Tulun commented on src/utils/onboardV2.ts
> +    },
There's a neat account modal thing that the render for you -- check it out here https://reactdemo.blocknative.com/

I assume this is not required for us.

2022-08-24 23:21 UTC, Tulun commented on src/state/connection.ts
>  };
This whole file should be deleted before PR is open.

2022-08-24 23:22 UTC, Tulun commented on src/hooks/useSendForm.tsx
>    /*
Only want to check this when the connected account changes not when the chainId changes from the user clicking their wallet..

2022-08-24 23:22 UTC, Tulun commented on src/hooks/useOnboard.tsx
> +import { useState, createContext } from "react";
Given that Onboard now exposes hooks, makes more sense to put it in something like context.

2022-08-25 15:33 UTC, Tulun commented
> Looks good, will test once ready

What's mostly left is the styling for the modal (checking in with tim) and any code cleanup. In theory could click around already :)

2022-08-29 05:27 UTC, mrice32 reviewed
This looks awesome. Nice work on ci!

Some of the reasoning and details weren't super clear to me, so it would be great if some other folks could take a close look at this, since it's a pretty high risk change.

2022-08-29 05:27 UTC, mrice32 commented on .github/workflows/lint-test.yaml
> +    services:
Nice!

2022-08-29 05:27 UTC, mrice32 commented on cypress/utils/CustomizedBridge.js
> +import { Wallet } from "@ethersproject/wallet";
Might be helpful to add comments to this file? Maybe just to document the overall purpose?

2022-08-29 05:27 UTC, mrice32 commented on src/hooks/useSendForm.tsx
> +      }
What happens if it's not a supported chain? Will swapping from supported to unsupported cause any issues in the dapp? Will the dapp know that transition happened?

2022-08-29 05:27 UTC, mrice32 commented on src/utils/onboard.ts
> +/*
What are all these comments?

2022-08-29 05:27 UTC, mrice32 commented on src/utils/onboard.ts
> +        enabled: false,
What does this mean?

2022-08-29 05:27 UTC, mrice32 commented on src/views/Pool.tsx
> +      // "",
nit: comment

2022-08-29 10:34 UTC, dohaki requested changes
Nice work with the e2e test improvements 🔥 I left a suggestion to add a `docker-compose.yml` maybe, and other small remarks. Some additions to the README.md on how to run the tests would also be nice. 

There is also a bug I encountered on the bridge page / home route. If you are disconnected and have selected an unsupported network in MetaMask, clicking on connect causes the following error
<img width="723" alt="image" src="https://user-images.githubusercontent.com/17645687/187181709-533c03c6-a0c3-49fa-8e94-5aea3fc69f1b.png">

2022-08-29 10:34 UTC, dohaki commented on .github/workflows/lint-test.yaml
> +      hardhat:
I think it would also make sense to add a `docker-compose.yml` file with similar settings, so that we can run the e2e tests locally in an easy way.

2022-08-29 10:34 UTC, dohaki commented on .github/workflows/lint-test.yaml
> +          NODE_OPTIONS: "--max-old-space-size=4096"
That is not needed here anymore, I think.

2022-08-29 10:34 UTC, dohaki commented on cypress/utils/ethereum.ts
> +console.log("DEFAULT_TEST_ADDRESS", DEFAULT_TEST_ADDRESS);
Can be removed

2022-08-29 12:14 UTC, daywiss approved these changes
code looks fine to me, seems like there was already some good comments. did some stress testing and did not see any issues using both coinbase and metamask, so thats really good

2022-08-29 15:56 UTC, Tulun commented on cypress/utils/CustomizedBridge.js
> +class CustomizedBridge extends Eip1193Bridge {
Just rested it with your implementation. It fails wit

The intention of this PR was not to rehash e2e stuff specifically, I want to kick this down the road and simply use what works for now. I wanna keep both and play around with it more later.

2022-08-29 15:56 UTC, Tulun commented on .github/workflows/lint-test.yaml
> +      hardhat:
Good idea.

2022-08-29 16:01 UTC, Tulun commented on cypress/utils/ethereum.ts
> +console.log("DEFAULT_TEST_ADDRESS", DEFAULT_TEST_ADDRESS);
Removed!

2022-08-29 16:02 UTC, Tulun commented on src/utils/onboard.ts
> +/*
Was for typing to help me figure out what options to pass. I can remove if desired :) (was a bit of hunting down in their own docs). Or I can refine it for clarity.

2022-08-29 16:05 UTC, Tulun commented on cypress/utils/CustomizedBridge.js
> +import { Wallet } from "@ethersproject/wallet";
Yup! I can do that. Basically, this is just our previously implemented Wallet from umaverse -- basically, we build a test implementation that can mock / return the values / methods we need to for our wallet to work on a fork in our e2e tests.

2022-08-29 16:07 UTC, Tulun commented on cypress/support/commands.ts
> +      // },
Yeah, I'm leaving in the previous wallet implementation because I want to kick it down the road -- the point of this PR wasn't necessarily going into a deep dive of e2e testing but Onboard failed with our current setup.

I'd rather have a PR focused on isolating this because I don't think our rudimentary tests should be a blocker, and see which wallet implementation works better for more robust testing.

2022-08-29 18:36 UTC, Tulun commented on src/utils/onboard.ts
> +        enabled: false,
There is a new feature in v2 where you have an account module you can render in your UI if you wish.

2022-08-29 18:36 UTC, Tulun commented on src/views/Pool.tsx
> +      // "",
removed.

2022-08-29 19:42 UTC, Tulun commented on .github/workflows/lint-test.yaml
> +      hardhat:
Added :)

2022-08-29 21:21 UTC, Tulun commented
> Nice work with the e2e test improvements 🔥 I left a suggestion to add a `docker-compose.yml` maybe, and other small remarks. Some additions to the README.md on how to run the tests would also be nice.
> 
> There is also a bug I encountered on the bridge page / home route. If you are disconnected and have selected an unsupported network in MetaMask, clicking on connect causes the following error <img alt="image" width="723" src="https://user-images.githubusercontent.com/17645687/187181709-533c03c6-a0c3-49fa-8e94-5aea3fc69f1b.png">

Tested this again it seems to connect ok?

2022-08-29 22:14 UTC, Tulun commented on README.md
> +1. Define HARDHAT_INFURA_ID to your desired infura project ID in .env.
Added.

2022-08-29 22:14 UTC, Tulun commented on src/state/hooks.ts
> +    ensName: account?.ens || undefined,
Fair, fixed.

2022-08-30 09:48 UTC, dohaki commented
@Tulun I am still having this issue on the bridge page 🤔 

https://user-images.githubusercontent.com/17645687/187406072-b6baff00-5c05-4181-a8e6-97ae662ba8f7.mov

2022-08-30 13:44 UTC, Tulun commented
> @Tulun I am still having this issue on the bridge page 🤔
> 
>  Screen.Recording.2022-08-30.at.11.46.22.mov

I was able to connect with MATIC. Hmm.

2022-08-30 13:57 UTC, Tulun commented
> @Tulun I am still having this issue on the bridge page 🤔
> 
>  Screen.Recording.2022-08-30.at.11.46.22.mov

Addressed, thanks for the video!

2022-08-30 14:05 UTC, dohaki approved these changes
👍

2022-08-30 14:30 UTC, mrice32 commented on src/utils/onboard.ts
> +        enabled: false,
Gotcha. So we're just leaving it as is for now. Makes sense.

2022-08-30 14:34 UTC, mrice32 approved these changes
LGTM!

2022-08-30 16:14 UTC, merged