Blockchain e2e tests
across-protocol/frontend-v2 pull request #252
Opened 2022-08-31 22:53 UTC by Tulun

1. bridge.cy.ts tests submitted a transaction.
2. getProvider returns our Mock Provider when window.isCypress = true
3. pool.cy.ts tests add and remove liquidity.

2022-09-01 13:15 UTC, daywiss requested changes

2022-09-01 13:15 UTC, daywiss commented on hardhat-scripts/helpers/createERC20ContractInstance.js
> +module.exports = async function createERC20ContractInstance(signer, networkId) {
you probably want to have address as a parameter here, or name this differently

2022-09-01 13:15 UTC, daywiss commented on src/hooks/useBalance.ts
> +    testProvider?: ethers.providers.Web3Provider;
i dont think this is the right approach to take here. The business logic should not be aware its in a testing environment if at all possible.  Would much rather you alter the constants file in the spots where providers are defined:

- add a new provider urls object called providerTestUrls [here](https://github.com/across-protocol/frontend-v2/blob/master/src/utils/constants.ts#L468)
- switch the variable providerUrlsTable based on if this is testing [here](https://github.com/across-protocol/frontend-v2/blob/master/src/utils/constants.ts#L484)

everything else should work the same after this point, as long as the app uses `getProvider` everywhere, [here](https://github.com/across-protocol/frontend-v2/blob/master/src/utils/constants.ts#L496)

2022-09-01 18:54 UTC, daywiss approved these changes
looks good!

2022-09-01 21:47 UTC, mrice32 reviewed
This is cool! One comment about the waiting.

2022-09-01 21:47 UTC, mrice32 commented on cypress/e2e/bridge.cy.ts
> +    cy.wait(6000);
These waits are interesting. Is this the recommended approach? It seems pretty inefficient as opposed to some sort of function that you could call that would allow you to _wait until the condition is met_ with a high timeout.

Note: in their docs, I see a call out that you _shouldn't_ need waits in your tests https://docs.cypress.io/guides/overview/why-cypress#Features.

2022-09-02 05:07 UTC, mrice32 approved these changes

2022-09-02 05:07 UTC, mrice32 commented on cypress/e2e/bridge.cy.ts
> +    cy.wait(7000);
Just OOC, why do we still need this wait?

2022-09-02 05:07 UTC, mrice32 commented on cypress/e2e/pool.cy.ts
> +    cy.wait(4000);
Same here.

2022-09-02 11:26 UTC, dohaki approved these changes
Nice 💪

2022-09-02 17:43 UTC, Tulun commented on cypress/e2e/bridge.cy.ts
> +    cy.wait(7000);
This one seems to fail without a wait.

2022-09-02 17:44 UTC, Tulun commented on cypress/e2e/pool.cy.ts
> +    cy.wait(4000);
> Same here.

This one was removable :)

2022-09-02 18:01 UTC, merged