feat: show warning if address is a non-EOA
across-protocol/frontend-v2 pull request #257
Opened 2022-09-02 18:32 UTC by Tulun

1. Check if address returned from Onboard is not an EOA. If so, warn users.

2022-09-02 21:03 UTC, mrice32 reviewed
Looks good! A few questions/suggestions.

2022-09-02 21:03 UTC, mrice32 commented on src/state/hooks.ts
> +            console.log("in here?", addr);
console

2022-09-02 21:03 UTC, mrice32 commented on src/state/hooks.ts
> +      // Note: Removed check for WETH and ETH because they can change tokens outside of this modal.
Isn't this outside of a modal anyway? This comment seems off? Regardless, I think we want to warn them even if it's not WETH since it's still dangerous to connect as a contract.

2022-09-02 21:26 UTC, Tulun commented on src/state/hooks.ts
> +            console.log("in here?", addr);
Removed!

2022-09-02 21:31 UTC, Tulun commented on src/components/SuperHeader/SuperHeader.tsx
> +  @media screen and (max-width: 768px) {
Adjusted.

2022-09-02 22:06 UTC, Tulun commented on src/state/hooks.ts
> +      // Note: Removed check for WETH and ETH because they can change tokens outside of this modal.
Removed.

2022-09-02 22:07 UTC, Tulun commented on src/state/hooks.ts
> +            console.log("in here?", addr);
Removed.

2022-09-02 22:30 UTC, Tulun commented on src/components/Banner/Banner.styles.tsx
>    width: 100%;
Fixed an issue where the sidebar wouldn't go over the banner.

2022-09-06 13:33 UTC, daywiss reviewed
code looks fine, but im not seeing the banner. instead im seeing the usdt disabled banner when i put in a contract address. 
![image](https://user-images.githubusercontent.com/4429761/188648502-1e917700-7cfe-49dd-8240-d2eab895a6f0.png)

2022-09-06 15:15 UTC, Tulun commented
> code looks fine, but im not seeing the banner. instead im seeing the usdt disabled banner when i put in a contract address. ![image](https://user-images.githubusercontent.com/4429761/188648502-1e917700-7cfe-49dd-8240-d2eab895a6f0.png)

Are you connected with a contract address (IE: Gnosis safe) or did you *set* your address?

2022-09-06 18:59 UTC, Tulun commented on src/state/hooks.ts
> +  const [showContractAddressWarning, setShowContractAddressWarning] =
Fair, renamed.

2022-09-06 19:01 UTC, daywiss commented
> Are you connected with a contract address (IE: Gnosis safe) or did you set your address?

no i misunderstood what triggered the message

2022-09-06 19:01 UTC, daywiss approved these changes

2022-09-06 19:13 UTC, mrice32 commented
This banner doesn't look right.

<img width="1728" alt="Screen Shot 2022-09-06 at 3 12 49 PM" src="https://user-images.githubusercontent.com/11791551/188719563-466853fe-3e4c-4051-ae37-4c99607e7395.png">

2022-09-06 19:13 UTC, mrice32 requested changes
https://github.com/across-protocol/frontend-v2/pull/257#issuecomment-1238552059

2022-09-06 21:33 UTC, mrice32 approved these changes
LGTM!

2022-09-06 21:43 UTC, merged