feat: :sparkles: add new optional parameter to serverless CG route
across-protocol/frontend-v2 pull request #258
Opened 2022-09-02 23:37 UTC by james-a-morris

This PR is aimed at adding an additional query parameter to the `api/coingecko` endpoint. When the optional `baseCurrency` is supplied, the endpoint will return the price of the token in terms of the specified currency. 

However, if the parameter is not supplied, the default case will be enabled which assumes a base currency of ETH (which is what is done today).

`baseCurrency` is not case sensitive. If it is not eth, btc, or usd, the SDK's symbol mapping will be used to look it up independently.

Breaking Changes: None. Everything is returned in terms of ETH today, so this works as expected.

2022-09-06 16:55 UTC, nicholaspai commented on api/_utils.js
> +const isStringNumeric = (value) => {
Why not just use `isNaN`? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isNaN

2022-09-06 16:56 UTC, nicholaspai commented on api/coingecko.js
> +    const price = await getTokenPrice(l1Token, Number(destinationId));
Currently all prices are returned with ETH as the denominator, does this PR break this assumption if we set the chainId to `137`? Or is returning with ETH as the denominator still expected?

2022-09-06 18:49 UTC, mrice32 reviewed
Just one high level comment!

2022-09-06 18:49 UTC, mrice32 commented on api/coingecko.js
> +    let { l1Token, destinationId } = request.query;
This seems to be more limiting than allowing the user to specify base currency. It also seems less natural for an endpoint that just provides price values.

For instance, one might imagine that an across bot wants to query the dollar value of a currency (the dataworker does this). Any reason not to have the caller figure out the appropriate base currency symbol for their chain and pass that instead?

Thoughts?

2022-09-07 19:06 UTC, mrice32 commented on api/coingecko.js
> +    let { l1Token, destinationId } = request.query;
Great points!!

Yeah, I think this endpoint should directly call the CG client so it can be general purpose. Ideally, we will actually have some sort of generalized class that can grab arbitrary prices that would be backed by this endpoint.

But would be interested to hear the rest of the team's feedback on that.

2022-09-07 19:07 UTC, mrice32 commented on api/coingecko.js
> +    let { l1Token, destinationId } = request.query;
Thoughts @nicholaspai?

2022-09-07 19:07 UTC, mrice32 reviewed
https://github.com/across-protocol/frontend-v2/pull/258#discussion_r965183330

2022-09-08 16:25 UTC, nicholaspai commented on api/coingecko.js
> +    let { l1Token, destinationId } = request.query;
I've talked with Matt and he's going to take over this PR. I think we should pay the upfront technical debt and have this `coingecko` endpoint instantiate the `BaseQuery` class to directly call the CG API and pass through the requested param's `baseCurrency`. This effectively implements Matt's suggestion to 

>  I think this endpoint should directly call the CG client so it can be general purpose

This will require some changes to #256 but we'll cross that road after this PR

2022-09-08 16:26 UTC, nicholaspai requested changes
https://github.com/across-protocol/frontend-v2/pull/258#discussion_r966172962

2022-09-09 07:05 UTC, pxrl commented on api/_utils.ts
> +  if (typeof queryFn === undefined) {
Is this working as intended? typeof produces a string, so won't this always evaluate false?

Separately, I did something similar and was encouraged to use:

```suggestion
  if (queryFn === undefined) {
```

2022-09-09 07:12 UTC, pxrl commented on api/_utils.ts
> +    throw new InputError("Invalid destination chain Id");
For any troubleshooting purposes that might arise it could be nice to include the actual chain ID that was supplied here:

```suggestion
    throw new InputError(`Invalid destination chain Id: ${chainId}`);
```

2022-09-09 07:14 UTC, pxrl commented on api/coingecko.ts
> +          "baseCurrency not supported in Coingecko and not found in address mapping"
Might also be nice to include the requested base currency in the log message:

```suggestion
          `base currency ${baseCurrency} not supported in Coingecko and not found in address mapping"
```

2022-09-09 07:20 UTC, pxrl commented on api/coingecko.ts
>      l1Token = ethers.utils.getAddress(l1Token);
Have you tested this with a range of upper-case addresses? I _think_ I've seen it throw exceptions on some addresses, and I _think_ that was because the first alpha character in the address was coincidentally upper-case in the checksummed version, so getAddress() decides it has been supplied a checksummed address and then gets upset when it's not.

From the ethers docs:

```
// Throws if a checksummed address is provided, but a
// letter is the wrong case
// ------------v (should be lower-case)
getAddress("0x8Ba1f109551bD432803012645Ac136ddd64DBA72")
// [Error: bad address checksum] {
//   argument: 'address',
//   code: 'INVALID_ARGUMENT',
//   reason: 'bad address checksum',
//   value: '0x8Ba1f109551bD432803012645Ac136ddd64DBA72'
// }
```

2022-09-09 08:03 UTC, pxrl commented on api/coingecko.ts
>      l1Token = ethers.utils.getAddress(l1Token);
I had a comment here about validating the length of l1Token and normalising it (in the event that it's supplied upper-case for some reason?), but realised that it's not really the focus of this review, and can see that the exception thrown by ethers is cleanly presented to the user. Just wanted to note it in case anyone saw the comment and was confused that it's gone.

2022-09-09 13:29 UTC, mrice32 commented on api/coingecko.ts
> +        console.log(price1, price2);
Oh, no, this was just a debug log that I mistakenly left there. WIll remove!

2022-09-09 13:31 UTC, mrice32 commented on api/_utils.ts
> +  if (typeof queryFn === undefined) {
Ah yes, great point. You're 100% right.

2022-09-09 13:31 UTC, mrice32 commented on api/_utils.ts
> +    throw new InputError("Invalid destination chain Id");
Agreed!

2022-09-09 13:31 UTC, mrice32 commented on api/coingecko.ts
> +          "baseCurrency not supported in Coingecko and not found in address mapping"
Good idea!

2022-09-09 20:49 UTC, mrice32 commented on api/coingecko.ts
> +    const cgBaseCurrency = baseCurrency.toLowerCase();
We don't, but we need an extra upper case in the else below.

2022-09-09 20:50 UTC, mrice32 commented on api/coingecko.ts
> +    const cgBaseCurrency = baseCurrency.toLowerCase();
Updated!

2022-09-09 20:50 UTC, mrice32 commented on api/coingecko.ts
> +        console.log(price1, price2);
Done!

2022-09-09 20:52 UTC, nicholaspai commented on api/_constants.ts
> +export const SUPPORTED_CG_BASE_CURRENCIES = new Set(["btc", "eth", "usd"]);
Is there any reason to add "btc" now versus just waiting until we need it?

2022-09-09 20:54 UTC, nicholaspai commented on api/coingecko.ts
> +          `base currency ${baseCurrency} not supported in Coingecko and not found in address mapping`
Does this error get thrown when the base current isn't supported in coingecko? It looks like it gets thrown only when we don't expect it, rather than looking it up against the CG API list explicity

2022-09-09 20:55 UTC, nicholaspai approved these changes
LGTM

2022-09-09 20:56 UTC, mrice32 commented on api/_constants.ts
> +export const SUPPORTED_CG_BASE_CURRENCIES = new Set(["btc", "eth", "usd"]);
Yeah, I didn't have a very good reason to do this. I think you're right.

2022-09-09 20:56 UTC, mrice32 commented on api/coingecko.ts
> +          `base currency ${baseCurrency} not supported in Coingecko and not found in address mapping`
Good point, I will update the language.

2022-09-09 20:57 UTC, mrice32 commented on api/coingecko.ts
> +          `base currency ${baseCurrency} not supported in Coingecko and not found in address mapping`
Updated.

2022-09-09 20:58 UTC, mrice32 commented on api/_constants.ts
> +export const SUPPORTED_CG_BASE_CURRENCIES = new Set(["btc", "eth", "usd"]);
Updated.

2022-09-09 21:43 UTC, merged