feat: integrate TX history logic
across-protocol/frontend-v2 pull request #27
Opened 2022-04-07 22:36 UTC by Tulun

Draft of implementation.

2022-04-08 14:53 UTC, daywiss commented on src/views/Transactions/useTransactionsView.ts
> +      startFetchingTransfers(account).then((res) => {
id suggest separating out this call from the interval. probably have a separate useEffect which listens to the account changing, clears the transaction state and a second useEffect which just continually polls the filled/pending transfers as long as account is defined

2022-04-08 15:32 UTC, Tulun commented on src/views/Transactions/useTransactionsView.ts
> +      startFetchingTransfers(account).then((res) => {
Yeah I'd like to better test different accounts with real transaction data if possible.

2022-04-08 17:38 UTC, daywiss reviewed
looking good

2022-04-08 17:38 UTC, daywiss commented on src/utils/format.ts
> +}).format;
im surprised this will work consistently without using `.bind`

2022-04-08 17:38 UTC, daywiss commented on src/views/Transactions/useTransactionsView.ts
> +async function startFetchingTransfers(account: string) {
this is a bit wierd, its  just a wrapper that nulls and logs an error

2022-04-08 17:46 UTC, Tulun commented on src/views/Transactions/useTransactionsView.ts
> +async function startFetchingTransfers(account: string) {
You can't put async function directly into a useEffect.

2022-04-08 22:23 UTC, mrice32 reviewed
Looks great! Some comments, but most are very minor.

2022-04-08 22:23 UTC, mrice32 commented on src/views/Transactions/useTransactionsView.ts
> +    if (account) {
What happens on account _change_? Does if the account changes without this being unmounted, does that account get tracked forever?

If you change and change back, will this throw an error because you've tracked the same account twice?

2022-04-08 22:23 UTC, mrice32 commented on src/views/Transactions/useTransactionsView.ts
> +import { Transfer } from "@across-protocol/sdk-v2/dist/transfers-history/model";
nit: prefer importing from `@across-protocol/sdk-v2` and drilling down in the object that that returns.

2022-04-08 22:23 UTC, mrice32 commented on src/state/transferHistory.ts
> +const chainConfigs = createTxHistoryClient();
nit: why are the chain configs returned by a function called createTxHistoryClient? I would expect that that function would return the client itself?

2022-04-08 22:23 UTC, mrice32 commented on src/views/Transactions/useTransactionsView.ts
> +        );
Why do we have a special catch just for this? Do we expect this to error often or is there something different about this error than, for instance, stopFetchingTransfers?

2022-04-08 22:23 UTC, mrice32 commented on src/views/Transactions/useTransactionsView.ts
> +      }, 5000);
nit: should this be a constant?

2022-04-08 22:23 UTC, mrice32 commented on src/views/Transactions/useTransactionsView.ts
> +        const nextFilledTx = txHistoryClient.getFilledTransfers(account);
cc @amateima @daywiss 

Something I want to make a note of here:

We have a client that does internal polling to determine the transfers and then we have UI logic to _poll that client_ on a second interval since the client can't write directly to app state.

I think this is a code smell.

I think this might be an example of why clients that manage their own request timings aren't well suited for our new frontend philosophy or really any frontend that doesn't allow these clients to directly write to the frontend state.

A few styles of clients that might work better:
1. A client where updates are triggered via a function call. After the update is called, data can be retrieved synchronously. I think this would basically be this current client without polling, but with an update function.
2. A client that's essentially a caching object. Async functions are called on the client to ask for specific pieces of data. New data is requested, but only data after the last call/update is pulled. Basically an object with async functions that do caching of past queries to make future queries easier.
3. No client. Just pure async functions with no caching.

Do y'all agree with this assessment? Or do y'all think we should manage the client interaction differently and I'm misunderstanding the tradeoff space here?

2022-04-08 22:51 UTC, mrice32 commented on src/views/Transactions/useTransactionsView.ts
> +      interval = setInterval(() => {
Is this somewhere where we could use react-query? Wouldn't it automate a lot of this logic for us?

Couldn't it poll, cache the state, and terminate the polling when one of the inputs changes?

2022-04-09 01:36 UTC, daywiss commented on src/views/Transactions/TransactionsTable/TransactionsTableWithPagination.tsx
> +      {paginatedRows.length > 25 && (
you could do somehting like this 
```
      {paginateState.totalPages > 1 ? (
        <PageNavigation onPageChange={setCurrentPage} {...paginateState} />
      ) : null}
```

2022-04-09 01:36 UTC, daywiss commented on src/views/Transactions/useTransactionsView.ts
> +    if (account) {
good q for @amateima

2022-04-09 01:36 UTC, daywiss commented on src/views/Transactions/useTransactionsView.ts
> +        const nextFilledTx = txHistoryClient.getFilledTransfers(account);
I'm not sure why theres a code smell. the way the client is designed its compatible with react query. You could set it up to poll/cache results from the calls.

Why do you say those designs will work better, is that because you think they technically will be better, the interfaces will be better or it conforms more to the design philosophy?

2022-04-11 08:46 UTC, Gamaranto commented on src/state/transferHistory.ts
> +// await client.startFetchingTransfers(<depositor_addr>);
stray comments (I think)

2022-04-11 08:46 UTC, Gamaranto commented on src/utils/bridge.ts
> +  // if (!isValidAddress(maybeAddress) || maybeAddress === ethers.constants.AddressZero) {
lets keep the check but add a "fake" value for the hub pool on mainnet imho

2022-04-11 08:46 UTC, Gamaranto commented on src/utils/constants.ts
> +export const PROVIDER_URLS: Record<ChainId, string> = {
this seems redundant with the `PROVIDERS` object in the `constants` file

2022-04-11 08:46 UTC, Gamaranto commented on src/utils/format.ts
> +}).format;
I agree with the comments, but I suggest we keep the object intact and then invoke the method on the object directly:
```javascript
export const formatNumberTwoSigDigits = new Intl.NumberFormat("en-US", {
  maximumSignificantDigits: 2,
});
// when consuming it in another file
formatNumberTwoSigDigits.format(yourNumber)
```

Which is the same way its used in the [MDN examples](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/format)

2022-04-11 08:46 UTC, Gamaranto commented on src/views/Transactions/TransactionsTable/MobileTransactionsTableWithPagination.tsx
> +      {paginatedRows.length > 25 && (
lets extract this to a variable, just to make it easier to find / change without having to look at the jsx, something like:
```javascript
const showPagination = paginatedRows.length > 25
```

in the function body

2022-04-11 08:46 UTC, Gamaranto commented on src/views/Transactions/TransactionsTable/createMobileTransactionTableJSX.tsx
> +Transfer:
stray comment

2022-04-11 08:46 UTC, Gamaranto commented on src/views/Transactions/TransactionsTable/createMobileTransactionTableJSX.tsx
> +    const token = TOKENS_LIST[1].find((x) => x.address === tx.assetAddr);
why is this always Ethereum Mainnet?

2022-04-11 08:46 UTC, Gamaranto commented on src/views/Transactions/TransactionsTable/createTransactionTableJSX.tsx
> +amount: BigNumber {_hex: '0x058d15e176280000', _isBigNumber: true}
stray comment

2022-04-11 08:46 UTC, Gamaranto commented on src/views/Transactions/useTransactionsView.ts
> +    if (account) {
My understanding is that the cleanup effect will run after an account change, before the next effect runs  https://github.com/donavon/hook-flow 
So the account will be untracked at each account change, before a subscription to the new account is made

2022-04-11 09:14 UTC, amateima requested changes

2022-04-11 09:14 UTC, amateima commented on src/state/transferHistory.ts
> +  pollingIntervalSeconds: 60000,
it is supposed to be specified in seconds

2022-04-11 09:14 UTC, amateima commented on src/views/Transactions/useTransactionsView.ts
> +        const nextFilledTx = txHistoryClient.getFilledTransfers(account);
I wouldn't use `setInterval` for polling the client. I added events in the client to avoid polling and rely only on events notifications

2022-04-11 18:30 UTC, Tulun commented on src/utils/bridge.ts
> +  // }
This was a temp fix -- re-added it back in.

2022-04-11 18:36 UTC, Tulun commented on src/utils/constants.ts
> +*/
Yes documentation.

2022-04-11 18:36 UTC, Tulun commented on src/state/transferHistory.ts
> +  pollingIntervalSeconds: 60000,
Fixed to 60.

2022-04-11 18:37 UTC, Tulun commented on src/views/Transactions/useTransactionsView.ts
> +        );
It's just to expose if an error happens in this particular call -- we can ignore it if you want, but not sure there's any harm being mindful if the SDK bugs out for debugging.

2022-04-11 18:39 UTC, Tulun commented on src/state/transferHistory.ts
> +const chainConfigs = createTxHistoryClient();
I could combine the chainConfigs in transferHistory -- I just wasn't sure if I was needing to be doing a bunch of formatting logic, as the sdk requires a specific format that's not currently built, but could possibly be combined from existing constants we have here.

2022-04-11 18:40 UTC, Tulun commented on src/views/Transactions/useTransactionsView.ts
> +      interval = setInterval(() => {
I doubt it would automate anything, as we are waiting for messages for the client. Whether or not we want to store the data in react-query is a different question. Basically, it would just be hard pushing this data into the data store as we aren't using react-query to actually call the API.

2022-04-11 18:40 UTC, Tulun commented on src/state/transferHistory.ts
> +// await client.startFetchingTransfers(<depositor_addr>);
Yup!

2022-04-11 18:41 UTC, Tulun commented on src/utils/constants.ts
> +export const PROVIDER_URLS: Record<ChainId, string> = {
Not exactly. The PROVIDERS object doesn't have this information -- I could extend it but I didn't necessarily want to touch the types there. It returns the PROVIDER instance not the URL, which is what the SDK wants.

But I figure it might require more refactoring than what it was worth.

2022-04-11 18:44 UTC, Tulun commented on src/views/Transactions/TransactionsTable/createMobileTransactionTableJSX.tsx
> +    const token = TOKENS_LIST[1].find((x) => x.address === tx.assetAddr);
Should be sourceChain, fixed.

2022-04-11 18:48 UTC, Tulun commented on src/views/Transactions/useTransactionsView.ts
> +import { Transfer } from "@across-protocol/sdk-v2/dist/transfers-history/model";
According to @amateima this is not currently exported -- he'll do it on next release.

2022-04-11 18:50 UTC, amateima commented on src/utils/constants.ts
> +export const PROVIDER_URLS: Record<ChainId, string> = {
@Tulun 
Hey, I can change the sdk to accept the Provider instances instead of the URLs. What do you think? This way we'd have less providers instantiated

2022-04-11 18:50 UTC, Tulun commented on src/views/Transactions/TransactionsTable/TransactionsTableWithPagination.tsx
> +      {paginatedRows.length > 25 && (
Like that better, fixed.

2022-04-11 19:09 UTC, Tulun commented
There are a couple bugs in the SDK that @amateima is going to fix -- we chatted about this on slack. He is going to expose the Transfer type and there is an issue in the stopFetching call that prevents it from actually fully stopping the interval.

Should be fixed tomorrow morning.

2022-04-11 19:09 UTC, Tulun commented on src/views/Transactions/useTransactionsView.ts
> +      }, 5000);
Removed interval :)

2022-04-11 19:15 UTC, Tulun commented on src/utils/format.ts
> +}).format;
I'm open to consensus on implementation.

2022-04-11 19:50 UTC, Tulun commented on src/utils/bridge.ts
> +  // if (!isValidAddress(maybeAddress) || maybeAddress === ethers.constants.AddressZero) {
Done!

2022-04-11 19:50 UTC, Tulun commented on src/utils/constants.ts
> +export const PROVIDER_URLS: Record<ChainId, string> = {
Sure, this seems reasonable to me.
@mrice32 @daywiss @Gamaranto

2022-04-12 10:21 UTC, daywiss commented on src/utils/constants.ts
> +export const PROVIDER_URLS: Record<ChainId, string> = {
i think thats fine

2022-04-12 19:59 UTC, mrice32 reviewed
@Tulun I realize now that I said something wrong in my previous comment. Once that's resolved, I think we should be good to go! Sorry about that!

2022-04-12 19:59 UTC, mrice32 commented on src/state/transferHistory.ts
> +const chainConfigs = createTxHistoryClient();
Not strongly opinionated! I would just change the name of the function if this is just returning a config!

2022-04-12 19:59 UTC, mrice32 commented on src/utils/constants.ts
> +export const PROVIDER_URLS: Record<ChainId, string> = {
SGTM!

2022-04-12 19:59 UTC, mrice32 commented on src/views/Transactions/useTransactionsView.ts
> +    if (account) {
@Gamaranto you're totally correct. I continue to mix this up.

@Tulun sorry for the misleading comment. We should be able to do something simpler here like:

```ts
useEffect(()  => {
  if (account) {
    txHistoryClient.startFetchingTransfers(account).catch((err) => {
      console.error(
          "Error in startFetchingTransfers call in txHistoryClient",
          err
        );
    });
    txHistoryClient.on(
        transfersHistory.TransfersHistoryEvent.TransfersUpdated,
        () => {
          console.log("does this fire", account);
          const nextFilledTx = txHistoryClient.getFilledTransfers(account);
          const nextOngoingTx = txHistoryClient.getPendingTransfers(account);

          setRawFilledTx(nextFilledTx);
          setRawOngoingTx(nextOngoingTx);
        }
      );
    return () => {
      txHistoryClient.stopFetchingTransfers(account);
    }
  }
}, [account]);
```

And we should be able to avoid all the previousAccount logic!

2022-04-14 19:00 UTC, Tulun commented
> [mrice32](https://github.com/mrice32) [2 days ago](https://github.com/across-protocol/frontend-v2/pull/27#discussion_r848819146)
@Gamaranto you're totally correct. I continue to mix this up.

@Tulun sorry for the misleading comment. We should be able to do something simpler here like:

useEffect(()  => {
  if (account) {
    txHistoryClient.startFetchingTransfers(account).catch((err) => {
      console.error(
          "Error in startFetchingTransfers call in txHistoryClient",
          err
        );
    });
    txHistoryClient.on(
        transfersHistory.TransfersHistoryEvent.TransfersUpdated,
        () => {
          console.log("does this fire", account);
          const nextFilledTx = txHistoryClient.getFilledTransfers(account);
          const nextOngoingTx = txHistoryClient.getPendingTransfers(account);

          setRawFilledTx(nextFilledTx);
          setRawOngoingTx(nextOngoingTx);
        }
      );
    return () => {
      txHistoryClient.stopFetchingTransfers(account);
    }
  }
}, [account]);
And we should be able to avoid all the previousAccount logic!


Still experiencing some SDK issues, but I'll try just adding the cleanup func.

2022-04-15 00:31 UTC, daywiss reviewed
there are still some minor outstanding comments but i think its good once resolved

2022-04-15 00:31 UTC, daywiss commented on src/views/Transactions/useTransactionsView.ts
> +import { Transfer } from "@across-protocol/sdk-v2/dist/transfers-history/model";
you should update this

2022-04-15 14:48 UTC, Gamaranto approved these changes
after other comments are addressed, looks good to me

2022-04-15 14:48 UTC, Gamaranto commented on src/utils/constants.ts
> +export const PROVIDER_URLS: Record<ChainId, string> = {
good to me!

2022-04-15 20:20 UTC, mrice32 approved these changes
LGTM!

2022-04-18 14:09 UTC, amateima approved these changes

2022-04-18 14:09 UTC, amateima commented on src/state/transferHistory.ts
> +  pollingIntervalSeconds: 5,
I would disable the polling for now until we add a proper Refresh button which will appear/enable when new data is available

2022-04-18 17:07 UTC, Tulun commented
> there are still some minor outstanding comments but i think its good once resolved

This type doesn't seem exposed yet in the sdk -- non blocking change. gonna kick it down for later.

2022-04-18 17:07 UTC, merged