feat: Banner notification
across-protocol/frontend-v2 pull request #48
Opened 2022-04-22 21:39 UTC by Tulun

Story details: https://app.shortcut.com/uma-project/story/5110
<img width="741" alt="Screen Shot 2022-04-22 at 2 38 19 PM" src="https://user-images.githubusercontent.com/12792146/164799390-7c0c3b9a-9d37-478f-9b1c-d0d55e1ca4a0.png">

2022-04-25 12:32 UTC, daywiss commented on src/views/Pool.tsx
> +                these instructions
clearly this text isnt right, we should wait until we have the right copy. also since this is going to show for everyone we should change the language a bit to be more of a suggestion to check v1 if you have liquidity.

2022-04-25 13:44 UTC, Tommy1231232 commented on src/views/Pool.tsx
> +                these instructions
In shortcut the verbiage was: "If you have not migrated liquidity from Across v1 to Across v2, please follow these instructions "

2022-04-25 14:38 UTC, Tommy1231232 requested changes
Update verbiage per comment

2022-04-25 15:11 UTC, Tulun commented on src/views/Pool.tsx
> +                these instructions
@Tommy1231232 verbiage updated. just lmk when the link is ready.

2022-04-26 16:48 UTC, Tommy1231232 commented on src/views/Pool.tsx
> +                these instructions
@Tulun I'm not seeing the banner on the pool tab. Not sure why I tried mainnet and kovan

2022-04-26 16:56 UTC, Tulun commented on src/views/Pool.tsx
> +                these instructions
@Tommy1231232 : you need to set REACT_APP_MIGRATION_POOL_V2_WARNING in your .env file to "true". 

We can do it on vercel if you really want.

2022-04-27 12:34 UTC, Tommy1231232 commented on src/views/Pool.tsx
> +                these instructions
@Tulun can you share a screenshot of the view you currently see?

2022-05-11 01:38 UTC, daywiss approved these changes
just need a card to remember to add link later

2022-05-11 14:40 UTC, mrice32 approved these changes

2022-05-12 16:03 UTC, Tulun commented
@mrice32 still waiting on a link.

2022-05-12 16:53 UTC, merged