improve: properly set amplitude environment
across-protocol/frontend-v2 pull request #669
Opened 2023-02-22 23:33 UTC by james-a-morris

This PR aims to correct the `AllAssetsAllNetworksWalletCurrentBalanceUsd` property that occurred since amplitude was not provided an environment.

2023-02-23 06:43 UTC, mrice32 approved these changes
LGTM!

2023-02-23 07:17 UTC, dohaki requested changes
I don't think that this fixes the issue tbh. The `environment` option is only used to determine an API key if we don't pass it explicitly.

2023-02-23 07:17 UTC, dohaki commented on src/App.tsx
> +    environment: isProductionBuild ? "production" : "development",
Hmm, I don't think that you need to pass that explicitly. Amplitude can derive the environment from the used API key AFAICT. Take a look at https://github.com/across-protocol/frontend-v2/blob/334011db6488b93a675bdc8efb4d0ddd5fa4a191/src/ampli/index.ts#L1295-L1309. The only time it uses the `environment` param, is when we don't pass an API key. That is the reason why I initially removed this from the config.

When you also take a look at the `this.amplitude.init` method, it doesn't use any `environment` value.

2023-02-24 12:20 UTC, james-a-morris commented on src/components/WalletBalanceTrace/useWalletBalanceTrace.ts
> +    return () => clearInterval(interval);
The retry logic is performed here. This PR also includes a reformat to align with the eslint config.

2023-02-24 12:23 UTC, james-a-morris commented
@dohaki I've added additional logic to proactively retry uploading the user property during a session until complete.

2023-02-24 12:48 UTC, dohaki reviewed
I couldn't verify that specifying the `environment` key actually fixes the issues, could you? If it doesn't, we should remove it from this PR IMO.

2023-02-24 12:48 UTC, dohaki commented on src/components/WalletBalanceTrace/useWalletBalanceTrace.ts
> +    return () => clearInterval(interval);
Can we add some max. retries here? I don't think that retrying indefinitely is a good practice. Alternatively, we could put that also into a `useQuery` hook where all the retry, etc. is already implemented.

2023-02-24 13:15 UTC, james-a-morris commented
> I couldn't verify that specifying the `environment` key fixes the issues; could you? If it doesn't, we should remove it from this PR, IMO.

Although I believe that, in this case, explicitly defining the production scope of Amplitude is a benefit to the codebase, I have removed it in this commit. 🙂  The primary verification I performed was that without setting this value, the preview branch was not correctly uploading to the correct dataset. I can add the environment key back if the problem is not resolved by adding this retry logic.

Good callout with the `react-query` 🔥

2023-02-24 13:32 UTC, dohaki approved these changes
Ok, nice. Yea weird when I tested it was correctly updating the user prop on Amplitude without specifying the environment key 🤔 Let's see. 

Looks good 👍 One last nit would be to remove the try/catch.

2023-02-24 13:32 UTC, dohaki commented on src/components/WalletBalanceTrace/useWalletBalanceTrace.ts
> +      }
NIT: We can actually remove the try/catch because we already log react-query failures to Sentry.

2023-02-24 14:10 UTC, merged