fix: :fire: disable the fees endpoints for 2.5 upgrade
across-protocol/frontend-v2 pull request #716
Opened 2023-04-24 15:44 UTC by james-a-morris

2023-04-24 15:51 UTC, dohaki requested changes
Looks good 👍 But can we wait before merging? I want to have a final Goerli test after updating to the latest packages/addresses

2023-04-25 13:29 UTC, mrice32 approved these changes
LGTM!

2023-04-25 13:29 UTC, mrice32 commented on api/_utils.ts
> +  return enabled && false; // TODO: This will disable all routes until we want to enable them
Just to make sure I'm understanding the logic, this will cause the suggested-fees and limits endpoints to always fail because every route is disabled, right? The other endpoints will continue to work correctly, right?

2023-04-25 13:36 UTC, dohaki approved these changes

2023-04-25 13:43 UTC, merged