feat: zk sync era support
across-protocol/frontend-v2 pull request #802
Opened 2023-08-07 14:56 UTC by dohaki

This adds support for bridging from/to zkSync Era mainnet and testnet.

Closes ACX-1335 and ACX-1350

**NOTE: Don't merge until testing is complete. Code can already be reviewed though.**

2023-08-09 14:01 UTC, james-a-morris approved these changes
LGTM - left some comments. My only worry is that the SVG's aren't ACX teal - but the CSS handles this fine.

2023-08-09 14:01 UTC, james-a-morris commented on api/_utils.ts
> +      return `http://127.0.0.1:3000`;
Is there a reason this needed to change?

2023-08-09 14:08 UTC, nicholaspai commented on api/_utils.ts
> +    new sdk.relayFeeCalculator.ZkSyncQueries(
@pxrl can you sanity check this is the correct way to construct this?

2023-08-09 14:08 UTC, nicholaspai commented on api/_utils.ts
> +      getProvider(1),
This seems like an error?

2023-08-09 14:09 UTC, nicholaspai commented on src/utils/constants.ts
> +    earliestBlock: 10352565,
Agreed i'm confused what this block is

2023-08-09 14:11 UTC, pxrl commented on api/_utils.ts
> +    new sdk.relayFeeCalculator.ZkSyncQueries(
This seems correct to me :+1:

2023-08-09 14:11 UTC, james-a-morris requested changes

2023-08-09 14:11 UTC, james-a-morris commented on api/_utils.ts
> +      getGasMarkup(1)
Similar to above @nicholaspai

2023-08-09 14:11 UTC, james-a-morris commented on api/_utils.ts
> +      getGasMarkup(42161)
These chain IDs do not match

2023-08-09 14:11 UTC, james-a-morris commented on api/_utils.ts
> +      getGasMarkup(324)
This is the wrong chain ID unless we are looking to mock 324

2023-08-09 14:13 UTC, pxrl commented on api/_utils.ts
> +      getProvider(324),
As discussed in the call yesterday, this seems intuitively wrong and I suspect it's in the class of "works by accident"...but it's a pre-existing pattern so I think we're OK to roll with it.

2023-08-09 15:28 UTC, dohaki commented on api/_utils.ts
> +      return `http://127.0.0.1:3000`;
Yea, for some reason `localhost` doesn't work correctly with the new `vite` setup.

2023-08-09 15:37 UTC, dohaki commented on api/_utils.ts
> +      getProvider(1),
I changed these queries because they weren't working previously. Because the dummy "from" address that's used to estimate gas costs isn't loaded on these test chains I guess. @pxrl mentioned that we use a similar approach in the relayer, so I implemented the workaround here.

Maybe I should add a comment that explains this?

2023-08-09 15:37 UTC, dohaki commented on api/_utils.ts
> +      getGasMarkup(1)
https://github.com/across-protocol/frontend-v2/pull/802/files#r1288744226

2023-08-09 15:38 UTC, dohaki commented on api/_utils.ts
> +      getProvider(324),
Yea, I used this workaround as explained in the call.

2023-08-09 15:47 UTC, dohaki commented on src/utils/constants.ts
> +    earliestBlock: 10352565,
AFAICT these values are the earliest block we consider or care about on the respective chains. In this case, this would be the block of the zkSync SpokePool deployment. But I noticed that we no longer use that in the code. So I will remove this to prevent further confusion.

2023-08-09 15:49 UTC, dohaki commented on src/utils/constants.ts
> +    earliestBlock: 10263886,
Removed here https://github.com/across-protocol/frontend-v2/pull/802/commits/a055917bb7581a3fed6a1751d4dfa8c63c78b733

2023-08-11 08:49 UTC, amateima approved these changes

2023-08-11 15:19 UTC, nicholaspai approved these changes

2023-08-11 16:05 UTC, merged