improve: condense disabled chains env variables
across-protocol/frontend-v2 pull request #829
Opened 2023-09-04 17:09 UTC by james-a-morris

The impetus for this PR is to reduce the number of environment variables that dictate which chains are available from two to one.

2023-09-04 22:20 UTC, dohaki requested changes
Refactoring looks good but left a question on the motivation behind this change

2023-09-04 22:20 UTC, dohaki commented on .env.example
> -REACT_APP_DISABLED_CHAINS_FOR_AVAILABLE_ROUTES=
The reason we had this second env var, was because we wanted to be able to enable certain chains for endpoints like `/suggested-feed` and `/limits` but disable them at the same time for other endpoints like `/available-routes`. Is this case something we won't need in the future or what is the motivation for this change?

2023-09-04 22:45 UTC, james-a-morris commented on .env.example
> -REACT_APP_DISABLED_CHAINS_FOR_AVAILABLE_ROUTES=
Thoughts on making this opt-in? I've added a change that includes the second variable but considers it a whitelist of chains we make visible via the available routes/token-list API endpoints.

I think have two thoughts that spurred my want for this change:

- Since the goal of this second var is to limit exposure of routes to aggregators - it may be beneficial to make it opt-in. 
- The naming conventions of the two are very similar, and we ran into an issue where the naming caused confusion & extra work.

2023-09-05 00:06 UTC, dohaki commented on .env.example
> -REACT_APP_DISABLED_CHAINS_FOR_AVAILABLE_ROUTES=
Isn't it already opt-in? We do not require a list of chains in the env var.

I agree that the previous name is a bit confusing but not sure if specifying an explicit list is also necessary.

Let's say, we add a new chain and want to test, then we need to add/remove all enabled chains from the new env var instead of adding/removing just the new chain id. So this could be more prone to errors because you need to keep track of multiple chain ids in contrast to a single one. 

I could also be a bit nitpicking here... Let me know what you think

2023-09-06 03:40 UTC, mrice32 commented on .env.example
> -REACT_APP_DISABLED_CHAINS_FOR_AVAILABLE_ROUTES=
Previously, would putting something in disabled chains disable it everywhere (including the routes)? Or would you have to put the disabled chain in both env arrays? If putting it in disabled chains was all that was needed for a full shutdown of a chain, maybe all we need is to make sure that variable is well documented for that purpose?

Not super strongly opinionated, just want this to be as clear as possible for use in cases like zkSync where fast shutdown is needed.

2023-09-07 02:30 UTC, mrice32 reviewed
https://github.com/across-protocol/frontend-v2/pull/829#discussion_r1316677860

2023-09-11 04:07 UTC, dohaki commented on .env.example
> -REACT_APP_DISABLED_CHAINS_FOR_AVAILABLE_ROUTES=
> Previously, would putting something in disabled chains disable it everywhere (including the routes)?

Yes. So we already had the env var `REACT_APP_DISBALED_CHAINS` which would disable the respective chains everywhere. For disabling a chain only on the `/available-routes` endpoint, you need to use the env var `REACT_APP_DISABLED_CHAINS_FOR_AVAILABLE_ROUTES`.

2023-09-11 04:08 UTC, dohaki commented on src/utils/constants.ts
> -).split(",");
I think we still need to keep track of the whitelisted available chains if we go with your approach.

2023-09-11 04:09 UTC, dohaki commented on src/views/Transactions/utils.ts
> -          )
We need to consider only the whitelisted chains here.

2023-09-11 04:13 UTC, dohaki commented on .env.example
> -REACT_APP_DISABLED_CHAINS_FOR_AVAILABLE_ROUTES=
After thinking a bit more about it, @james-a-morris approach seems actually better. Because we only need to update the whitelist env var only once when we want to enable the new chain. Instead of updating twice (adding the to be disabled chain and removing it again).

2023-09-11 04:13 UTC, dohaki commented
@james-a-morris I left only two comments on the transactions page but if these are addressed this looks good to me

2023-09-15 13:22 UTC, james-a-morris commented on .env.example
> -REACT_APP_DISABLED_CHAINS_FOR_AVAILABLE_ROUTES=
Sounds good to me!

2023-12-18 23:56 UTC, closed without merging