feat: add balancer to base routes
across-protocol/frontend-v2 pull request #839
Opened 2023-09-05 16:44 UTC by james-a-morris

2023-09-06 00:34 UTC, dohaki approved these changes

2023-09-07 02:30 UTC, mrice32 commented
As discussed IRL, we're going to hold off on this until confusion over the correct address subsides!

2023-09-30 19:40 UTC, nicholaspai requested changes
We might need to import contracts-v2 version 2.4.4 which includes the updated TOKEN_SYMBOLS_MAPPING with the new BAL address

But otherwise this LGTM when we want to enable BAL on Base

2023-10-06 14:08 UTC, nicholaspai approved these changes

2023-10-06 14:12 UTC, merged