fix: base currency conversions for fee preview
across-protocol/frontend-v2 pull request #937
Opened 2023-12-08 16:47 UTC by dohaki

Fixes base currency conversions on the fee preview for values > 1k. 

The root cause was again unexpected behavior of the helper `formatUSD`. I have seen quite a few bugs recently due to this function. From what I can tell, the function's naming suggests something else than it does. We should refactor the name soon.

2023-12-08 16:49 UTC, dohaki commented on src/views/Bridge/hooks/useEstimatedTable.ts
> -    const formatNumericUsd = (usd: BigNumber) => Number(formatUSD(usd));
It was failing here. If the arg `usd` was a number > 1k, then the `formatUSD` helper would format it to a human readable custom format like `1,000`. This would then return `NaN` if trying to parse to a `number`.

2023-12-08 17:14 UTC, james-a-morris approved these changes

2023-12-08 17:17 UTC, james-a-morris requested changes
Left a comment

2023-12-08 17:17 UTC, james-a-morris commented on src/views/Bridge/hooks/useEstimatedTable.ts
> +          .div(fixedPointAdjustment)
@dohaki does doing this impact the table estimates?

The reason the code was written this way was so that the numbers always add up to the total fee. There's a rounding issue that occasionally happens where the total fee is off by one cent and that's just a result of the conversion rates I think we should keep it as is and we should just change the bug which is in format USD to remove the commas.

2023-12-09 00:58 UTC, james-a-morris approved these changes
LGTM - changes made post sync seem to work well

2023-12-09 01:01 UTC, merged